name: Bug report
labels: ["bug"]
body:
  - type: input
    id: unity
    attributes: { label: Unity version }
  - type: input
    id: rp
    attributes: { label: Render pipeline (Built-in/URP/HDRP) }
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce }
  - type: textarea
    id: logs
    attributes: { label: Console errors/warnings }
